# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://cdn.cocoapods.org/'

target 'UnitTestWithPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnitTestWithPod
  pod 'KeychainSwift'
  pod 'gRPC-Swift', '1.0.0'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
    if target.name == "gRPC-Swift" || target.name == "SwiftNIO" || target.name == "SwiftNIOConcurrencyHelpers" || target.name == "SwiftNIOExtras" || target.name == "SwiftNIOFoundationCompat" || target.name == "SwiftNIOHPACK" || target.name == "SwiftNIOHTTP1" || target.name == "SwiftNIOHTTP2" || target.name == "SwiftNIOSSL" || target.name == "SwiftNIOTLS" || target.name == "SwiftNIOTransportServices"
      target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      end
    end
  end
end











