# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://cdn.cocoapods.org/'
target 'UnitTestWithPodAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnitTestWithPodAPP
  #pod 'UnitTestWithPod', :podspec => 'https://raw.githubusercontent.com/LLTemp/test_sic_zip/main/UnitTestWithPod.podspec'
  #pod 'UnitTestWithPod', :podspec => '../UnitTestWithPod/UnitTestWithPod.podspec'
  pod 'UnitTestWithPod', :path => '../UnitTestWithPod'


end
