# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://cdn.cocoapods.org/'
target 'UnitTestWithPodAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for UnitTestWithPodAPP
  #pod 'UnitTestWithPod', :podspec => 'https://raw.githubusercontent.com/LLTemp/test_sic_zip/main/1.2.1/UnitTestWithPod.podspec'
  
  #pod 'UnitTestWithPod', :path => '../UnitTestWithPod/'
  pod 'Firebase/Messaging'
  #pod 'KeychainSwift'
  
  
  
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  #pod 'Firebase/AppDistribution'

end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#    end
#  end
#end

