name: SIC Example App

on:
  push:
    branches: [ master ]
    paths:
      - 'UnitTestWithPodAPP/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'UnitTestWithPodAPP/**'

defaults:
  run:
    working-directory: ./UnitTestWithPodAPP

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

# Actions to run example application
    - name: pod_install_lib
      run: pod install