name: SIC Example App

on:
  push:
    branches: [ master ]
    paths:
      - 'UnitTestWithPodAPP/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'UnitTestWithPodAPP/**'

defaults:
  run:
    working-directory: ./UnitTestWithPodAPP

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

# Actions to run example application
#    - name: Pod install
#      run: pod install
#
#    - name: Run unit tests
#      run: xcodebuild test -workspace ./UnitTestWithPodApp.xcworkspace -scheme UnitTestWithPodAPPTests ONLY_ACTIVE_ARCH=YES CODE_SIGN_REQUIRE=NO -destination "platform=iOS Simulator,OS=14.2,name=iPhone 8"
#
#    - name: Archive test report
#      if: ${{ always() }}
#      uses: actions/upload-artifact@v2
#      with:
#        name: Coverage
#        path: /Users/runner/Library/Developer/Xcode/DerivedData/UnitTestWithPodAPP-aixaeyjiavyyshfgxjwdsrcmncun/Logs/Test/*.xcresult
#
#    - name: Create keychain
#      if: ${{ github.event_name == 'push' }}
#      env:
#        P12_SECRET: ${{ secrets.P12_SECRET }}
#      run: ./scripts/add-key.sh
#
#    - name: Build archive
#      run: |
#        xcodebuild -workspace ./UnitTestWithPodAPP.xcworkspace -scheme UnitTestWithPodAPP -sdk iphoneos -configuration Release archive -archivePath ./build/UnitTestWithPodAPP.xcarchive
#        xcodebuild -exportArchive -archivePath ./build/UnitTestWithPodAPP.xcarchive -exportOptionsPlist ./scripts/exportOptions.plist -exportPath ./build
#
#    - name: Archive Archive
#      if: ${{ always() }}
#      uses: actions/upload-artifact@v2
#      with:
#        name: UnitTestWithPodAPP.xcarchive
#        path: UnitTestWithPodAPP/build/UnitTestWithPodAPP.xcarchive

    - name: Install firebase tools
      if: ${{ github.event_name == 'push' }}
      run: npm install -g firebase-tools

    - name: Upload to Firebase
      if: ${{ github.event_name == 'push' }}
      env:
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: ./scripts/firebase_upload.sh


