name: SIC Example App

on:
  push:
    branches: [ master ]
    paths:
      - 'UnitTestWithPodAPP/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'UnitTestWithPodAPP/**'

defaults:
  run:
    working-directory: ./UnitTestWithPodAPP

jobs:
  build:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

############## Calculate versions
    - name: Calculate versions
      working-directory: ./
      run: 'node projectsVersions.js'

    - name: Print versions
      run: |
        version=$(<VERSION)
        echo "Version = $version"


############## Installing dependencies
    - name: Pod install
      run: |
        rm Podfile.lock
        pod install


############## Testing application
    - name: Run unit tests
      run: xcodebuild test -workspace ./UnitTestWithPodApp.xcworkspace -scheme UnitTestWithPodAPPTests ONLY_ACTIVE_ARCH=YES CODE_SIGN_REQUIRE=NO -destination "platform=iOS Simulator,OS=14.2,name=iPhone 8"

    - name: Archive test report
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Coverage
        path: /Users/runner/Library/Developer/Xcode/DerivedData/UnitTestWithPodAPP-aixaeyjiavyyshfgxjwdsrcmncun/Logs/Test/*.xcresult

############## Signing and upload
    - name: Signing and upload
      if: contains(env.commitmsg, 'upload_source') && ${{ github.event_name == 'push' }}
      env:
        P12_SECRET: ${{ secrets.P12_SECRET }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        GROUPS_LIST: ${{ secrets.GROUPS_LIST }}
      run: ./scripts/sign_and_upload.sh




############### Signing and archiving application
#    - name: Create keychain
#      if: contains(env.commitmsg, 'upload_source') && ${{ github.event_name == 'push' }}
#      env:
#        P12_SECRET: ${{ secrets.P12_SECRET }}
#      run: ./scripts/add-key.sh
#
#    - name: Build archive
#      if: contains(env.commitmsg, 'upload_source') && ${{ github.event_name == 'push' }}
#      run: |
#        xcodebuild -workspace ./UnitTestWithPodAPP.xcworkspace -scheme UnitTestWithPodAPP -sdk iphoneos -configuration Release archive -archivePath ./build/UnitTestWithPodAPP.xcarchive
#        xcodebuild -exportArchive -archivePath ./build/UnitTestWithPodAPP.xcarchive -exportOptionsPlist ./scripts/exportOptions.plist -exportPath ./build
#
#
############### Uploading application to Firebase
#    - name: Install firebase tools
#      if: contains(env.commitmsg, 'upload_source') && ${{ github.event_name == 'push' }}
#      run: npm install -g firebase-tools
#
#    - name: Upload to Firebase
#      if: contains(env.commitmsg, 'upload_source') && ${{ github.event_name == 'push' }}
#      env:
#        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
#        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#        GROUPS_LIST: ${{ secrets.GROUPS_LIST }}
#      run: ./scripts/firebase_upload.sh
#
#
#   TODO: do we need upload source code of the app to separate repository?
#    - name: Upload source code to other repo
#      if: ${{ github.event_name == 'push' }}
#      env:
#        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
#        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#        GROUPS_LIST: ${{ secrets.GROUPS_LIST }}
#      run: ./scripts/firebase_upload.sh
