name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: pod_install_lib
      run: pod install --project-directory=./UnitTestWithPod

#    - name: pod_install_app
#      run: pod install --project-directory=./UnitTestWithPodApp

    - name: test_sdk
      run: xcodebuild test -workspace ./UnitTestWithPod/UnitTestWithPod.xcworkspace -scheme UnitTestWithPodTests ONLY_ACTIVE_ARCH=YES CODE_SIGN_REQUIRE=NO -destination "platform=iOS Simulator,OS=14.0,name=iPhone 8"

    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: /Users/runner/Library/Developer/Xcode/DerivedData/UnitTestWithPod-fznsrnskqxpbyodcpeiavrncgppz/Logs/Test/*.xcresult

    - name: ls
      run: ls -la

    - name: zip_sdk
      run: zip -r UnitTestWithPod.framework.zip UnitTestWithPod/UnitTestWithPod.framework

    - name: ls2
      run: ls -la

