name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

#    - name: pod_install_lib
#      run: pod install --project-directory=./UnitTestWithPod
#
#    - name: pod_install_app
#      run: pod install --project-directory=./UnitTestWithPodApp
#
#    - name: test_sdk
#      run: xcodebuild test -workspace ./UnitTestWithPod/UnitTestWithPod.xcworkspace -scheme UnitTestWithPodTests ONLY_ACTIVE_ARCH=YES CODE_SIGN_REQUIRE=NO -destination "platform=iOS Simulator,OS=14.0,name=iPhone 8"
#
#    - name: Archive test report
#      uses: actions/upload-artifact@v2
#      with:
#        name: Coverage
#        path: /Users/runner/Library/Developer/Xcode/DerivedData/UnitTestWithPod-fznsrnskqxpbyodcpeiavrncgppz/Logs/Test/*.xcresult
#
#    - name: Create framework
#      run: xcodebuild -workspace ./UnitTestWithPod/UnitTestWithPod.xcworkspace -scheme Universal ONLY_ACTIVE_ARCH=YES CODE_SIGN_REQUIRE=NO
#
#    - name: zip_sdk
#      run: zip -r UnitTestWithPod.framework.zip ./UnitTestWithPod/UnitTestWithPod.framework


    - name: Get sha1 of existing file
      run: |
      latestCommit=$( curl -X GET -H "Authorization: token c4ace1752e8cd4a6572002b842874f142039e9cf" "https://api.github.com/repos/LLTemp/test_sic_zip/commits?&per_page=1" | jq '.[0].sha' -r)
      curl -X GET -H "Authorization: token c4ace1752e8cd4a6572002b842874f142039e9cf" "https://api.github.com/repos/LLTemp/test_sic_zip/git/trees/${latestCommit}" | jq '.tree[] | select(.path == "UnitTestWithPod.framework.zip") | .sha' -r


#    - name: Prepare for uploading
#      run: |
#        openssl base64 -in ./UnitTestWithPod.framework.zip -out base64.txt -A
#        base64content=$(cat base64.txt)
#        sha1content=$(curl \
#              -X GET \
#              -H "Accept: application/vnd.github.v3+json" \
#              -H "Authorization: token c4ace1752e8cd4a6572002b842874f142039e9cf" \
#                https://api.github.com/repos/LLTemp/test_sic_zip/contents/UnitTestWithPod.framework.zip | jq .sha -r)
#        echo "{\"message\":\"from curl\", \"content\":\"${base64content}\", \"sha\":\"${sha1content}\"}" > body.json

    - name: LS
      run: ls -la ./UnitTestWithPod